name: portfolio CI/CD

on:
  push:
    branches:
      - devOpsLearning
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: docker build and run
        run: |
          docker build -f Dockerfile.prod -t portfolio-app .
          docker run -d -p 3000:3000 portfolio-app
